name: Continuous Integration

on: 
  push:
    branches:
      - '**'
jobs:
  Lint-and-Build-and-Test:
    runs-on: ubuntu-latest
    env:
      WHO_AM_I: ${{ secrets.WHO_AM_I  }}
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Add Build version
        id: add-build-version
        run: |
          echo "app_build=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_OUTPUT
          echo $(date +'%Y%m%d.%H%M%S')
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
          echo "github.ref_name = ${GITHUB_REF_NAME}"
          echo "github.ref = ${GITHUB_REF}"
          echo "github.event.workflow_run.head_branch = ${HEAD_BRANCH}"
        env:
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install App Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint App
        run: |
          echo "Linting app..."
          sleep 10

      - name: Build App
        run: |
          echo "Building app..."
          sleep 10

      - name: Test App
        env:
          APP_BUILD: ${{ steps.add-build-version.outputs.app_build }}
        run: |
          echo "Testing app..."
          sleep 10
          node app.js