name: Release

on: 
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      WHO_AM_I: ${{ secrets.WHO_AM_I  }}
    strategy:
      fail-fast: true
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check if other push workflows are running
        id: wait
        uses: actions/github-script@v4
        with:
          script: |
            const completedWorkflows = github.event.workflow_run.conclusion;
            const pushWorkflows = github.event.workflow_run.repository.workflows.edges
              .map(edge => edge.node)
              .filter(node => node.event === 'push' && node.status !== 'COMPLETED')
              .map(node => node.name);

            if (pushWorkflows.length > 0) {
              console.log(`Waiting for push workflows: ${pushWorkflows.join(', ')}`);
              return { wait: true };
            } else {
              console.log('No push workflows in progress. Proceeding with tag workflow.');
              return { wait: false };
            }
            - uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
          echo "github.ref_name = ${GITHUB_REF_NAME}"
          echo "github.ref = ${GITHUB_REF}"
          echo "github.event.workflow_run.head_branch = ${HEAD_BRANCH}"
        env:
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install App Dependencies
        run: yarn install --frozen-lockfile

      - name: Run app
        run: node app.js
    